### ISSUE TITLE
Do I have to start a new game for the mods to take effect?

### ISSUE THREAD

**Issue by kamalsprasad** [NinjasCL/stardewvalley-veganmod#1]
I started playing Stardew Valley not long ago and being vegan myself looked for a mod that didn't require me to use animals. So, I was really excited to find this mod. I copied the files to the appropriate locations but I'm still getting a "start a chicken coop" mission after I harvest the parsnips for the first time. I didn't start a new game after applying the mode. Just loaded my save game. Does this make a difference?

**Comment by clsource** [comment]
Hello, thanks for using my mod and being vegan 💯  😄 .

Well maybe the mod is not working quite well in the latest version 1.2 released not so long ago.
The mod was tested on 1.1.

I will be working on a tool that enables you to create your own mods for the community center arc so it will be easier to make modifications 👍

**Comment by kamalsprasad** [comment]
Great. Looking forward to this. Thanks for making the mod so us vegans can really enjoy the game without feeling bad. 👍

**Comment by clsource** [comment]
Thanks !.
Also keep in mind this mod only modifies the community center items. So you don't need to use animal products for completing that arc.

Other game behaviors or events are not modified. Thankfully creating a chiken coop, fishing, milking, honey, etc. are all optional. Stardew Valley is great because you can play the way you want 👍
